version: '3'
services:
  database:
    container_name: database
    image: postgis/postgis:13-master
    restart: always
    networks:
      - directus-network
    env_file:
      - ./.env
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:

  directus:
    container_name: directus
    image: directus/directus:latest
    volumes:
      - ./uploads:/directus/uploads
    env_file:
      - ./.env
    networks:
      - web
      - directus-network
    depends_on:
      - database
    environment:

    labels:
      - traefik.enable=true
      - traefik.http.services.EASYSELLING.loadbalancer.server.port=8055
      - traefik.http.routers.EASYSELLING.rule=Host(`alcall.pierregourgouillon.com`)
      - traefik.http.routers.EASYSELLING.entrypoints=http
      - traefik.http.routers.EASYSELLING.middlewares=https-redirect@file
      - traefik.http.routers.EASYSELLING-Https.rule=Host(`alcall.pierregourgouillon.com`)
      - traefik.http.routers.EASYSELLING-Https.entrypoints=https
      - traefik.http.routers.EASYSELLING-Https.middlewares=security@file, compression@file
      - traefik.http.routers.EASYSELLING-Https.tls=true
      - traefik.http.routers.EASYSELLING-Https.tls.certresolver=letsencrypt
networks:
  directus-network:
  web:
    external: true