version: '3'
services:
  database:
    container_name: database
    image: postgis/postgis:13-master
    restart: always
    networks:
      - directus-network
    env_file:
      - ./.env
    volumes:
      - ./data/database:/var/lib/postgresql/data

  directus:
    container_name: directus
    image: directus/directus:latest
    volumes:
      - ./uploads:/directus/uploads
    env_file:
      - ./.env
    networks:
      - web
      - directus-network
    depends_on:
      - database
    labels:
      - traefik.enable=true
      - traefik.http.services.ALCALL.loadbalancer.server.port=8055
      - traefik.http.routers.ALCALL.rule=Host(`alcall.pierregourgouillon.com`)
      - traefik.http.routers.ALCALL.entrypoints=http
      - traefik.http.routers.ALCALL.middlewares=https-redirect@file
      - traefik.http.routers.ALCALL-Https.rule=Host(`alcall.pierregourgouillon.com`)
      - traefik.http.routers.ALCALL-Https.entrypoints=https
      - traefik.http.routers.ALCALL-Https.middlewares=security@file, compression@file
      - traefik.http.routers.ALCALL-Https.tls=true
      - traefik.http.routers.ALCALL-Https.tls.certresolver=letsencrypt
networks:
  directus-network:
  web:
    external: true